version: '3.4'

services:
  grafana:
    container_name: grafana
    build: 
      dockerfile: Dockerfile
      context: ./grafana
    ports:
      - 3555:3555

  prometheus:
    container_name: prometheus
    build: 
      dockerfile: Dockerfile
      context: ./prometheus
    ports:
      - 9090:9090

  # grpcclient:
  #   container_name: grpcclient
  #   build:
  #     dockerfile: ./grpcclient/Dockerfile
  #     context: ./

  promclient:
    container_name: promclient
    build:
      dockerfile: ./promclient/Dockerfile
      context: ./
    ports:
      - 5555:5555
      - 5556:5556

  # annotation-generator:
  #   container_name: annotation-generator
  #   build:
  #     dockerfile: ./annotation-generator/Dockerfile
  #     context: ./