version: '3.4'

services:
  base:
    container_name: base
    build:
      dockerfile: Dockerfile
      context: ./

  grafana:
    build: 
      dockerfile: Dockerfile
      context: ./grafana
    ports:
      - 3555:3555

  prometheus:
    build: 
      dockerfile: Dockerfile
      context: ./prometheus
    ports:
      - 9090:9090

  grpcclient:
    build:
      dockerfile: Dockerfile
      context: ./grpcclient

  promclient:
    build:
      dockerfile: Dockerfile
      context: ./promclient
    ports:
      - 5555:5555
      - 5556:5556

  annotation-generator:
    depends_on:
      - prometheus
      - grafana
    build:
      dockerfile: Dockerfile
      context: ./annotation-generator