version: '3.4'

services:
  grafana:
    build: 
      dockerfile: Dockerfile
      context: ./grafana
    ports:
      - 3555:3555

  prometheus:
    build: 
      dockerfile: Dockerfile
      context: ./prometheus
    ports:
      - 9090:9090